### ISSUE TITLE
Xpress Huffman max compressed size is unreasonable

### ISSUE THREAD

**Issue by nemequ** [coderforlife/ms-compress#13]
`ms_max_compressed_size (MSCOMP_XPRESS_HUFF, 2725) == 18446744073709551615` here.  I guess it's technically not *wrong*…  I'm sure that would be enough space… ;)

**Comment by coderforlife** [comment]
Oddly that has that bit pattern 0001 1001 1001 1001 ... suspicious.

**Comment by coderforlife** [comment]
The actual value should be 2985 which has the bit pattern 1101 1010 1001 which has some similarities...

**Comment by coderforlife** [comment]
I am unable to reproduce this. I always get the expected 2985.

I have tried with MSVC 18.00.30723 and GCC 4.9.2 (i686-posix-dwarf-rev1, Built by MinGW-W64 project).

With MSVC I have tried 32-bit and 64-bit, debug and release, static and dynamic linked. GCC was only 32-bit and dynamically linked.

Do other numbers work? Does call xpress_huff_max_compressed_size directly work?

**Comment by nemequ** [comment]
No, I get the same value for all inputs.  GCC 4.9.2 Linux 3.18.7 x86_64 (Fedora 21).

I'll try to figure it out myself—shouldn't be too hard.

**Comment by coderforlife** [comment]
Are you compiling without Xpress Huffman support? Then ms_* functions return errors, and for that one it is (size_t)-1, but I would expect that to be 0xFFFF... not the strange thing you get.

Check calling xpress_huff_max_compressed_size directly.

**Comment by nemequ** [comment]
Just built from a fresh checkout and it works.  I'm was on ce1d61cf62fc8060e2f542de687a7cfec2df9b57 before, and it was failing in multiple copies (squash's internal copy and a separate unmodified checkout).  Maybe 74101ccad397f56e9b2e7646284129ee5092afdf fixed it?

Anyways, works now, closing.

**Comment by coderforlife** [comment]
Everything since ce1d61c should have had no effect (the one you mentioned only changed a python testing script so I could test). No idea what was going on.
