### ISSUE TITLE
xpress huff doesn't handle random data, or very short buffers, well

### ISSUE THREAD

**Issue by nemequ** [coderforlife/ms-compress#14]
```
#include "include/mscomp.h"

#define CODEC MSCOMP_XPRESS_HUFF

int main(int argc, char *argv[])
{
  uint8_t uncompressed[8192];
  size_t uncompressed_length = 0;
  uint8_t compressed[32768];
  size_t compressed_length;
  uint8_t decompressed[8192];
  size_t decompressed_length;

  MSCompStatus status;

  {
    int i;
    for (i = 0 ; i < sizeof (uncompressed) ; i++) {
      uncompressed[i] = (uint8_t) (rand () & 0xff);
    }
  }

  for (uncompressed_length = 1 ; uncompressed_length < sizeof(uncompressed) ; uncompressed_length++) {
    compressed_length = ms_max_compressed_size (CODEC, uncompressed_length);
    assert (compressed_length < sizeof(compressed));

    status = ms_compress(CODEC, uncompressed, uncompressed_length, compressed, &compressed_length);
    assert (status == MSCOMP_OK);

    decompressed_length = uncompressed_length;
    status = ms_decompress(CODEC, compressed, compressed_length, decompressed, &decompressed_length);
    if (status != MSCOMP_OK)
      fprintf (stderr, "%zu bytes failed: ms_decompress returned %d, expected %d\n", uncompressed_length, status, MSCOMP_OK);
    assert (status == MSCOMP_OK);
  }

  return 0;
}
```

Change CODEC to LZNT1 or XPRESS and it works as expected.

**Comment by coderforlife** [comment]
Lots of problems here. If I remove various checks of yours I can properly compress up to 30 byte strings. I can't decompress a 1 byte string even when I give it super-large buffer (and in this case an assert within the Xpress Huffman code is triggered!). Even if I am giving the decompressor invalid data I should not be triggering an assert.

**Comment by coderforlife** [comment]
Please check if this is fixed. My test shows that it is. I also threw in some code to show me how much better than max size we were doing. It frequently hits 0 and 1 with random data, but never worse than 0, so I think the max function is now right along with uncompressible-handler I added.

The basic problem was this:
In compression I was not adding the end-of-stream symbol properly when data was uncompressible. In decompression if the end-of-stream never came it over-read from the data. Both of these have been fixed.

**Comment by nemequ** [comment]
I still get an assertion failure with the test case from my comment:

> src/xpress_huff_compress.cpp:313: MSCompStatus xpress_huff_compress(const_bytes, size_t, bytes, size_t*): Assertion `comp_len <= in_len+4' failed.

Happens at a length of 7325 with this data: http://code.coeusgroup.com/ms-compress-random.data

That said, it is now passing the random-data unit test in Squash, but that's not quite as exhaustive as what I posted here.

**Comment by coderforlife** [comment]
That is an indication that I am getting larger than the max-compressed-size. Thanks for a concrete example of that. I have tested lots of sequences, but didn't find one yet. I will look into why that one goes over and if there would be a way to fix it.

**Comment by coderforlife** [comment]
I added 2 to the max_compressed_size, I hope that is enough. I thought I had the theoretical limit, but I guess not.

**Comment by nemequ** [comment]
Sorry, should have mentioned a long time ago that this works for me.  As far as I'm concerned this issue can be closed.
