### ISSUE TITLE
Decompression crashes under mingw-w64

### ISSUE THREAD

**Issue by jibsen** [coderforlife/ms-compress#28]
I am seeing some crashes in xpress-huffman when running the new squash decompression test compiled with mingw-w64 on Windows.

Specifically, it is the memset on [line 67](https://github.com/coderforlife/ms-compress/blob/master/include/mscomp/HuffmanDecoder.h#L67) in HuffmanDecoder.h. I've tracked it down to an overflow in the computation of `last` a few lines above, resulting in a state where `index > limit`.

The code works with MSVC, because it happens to use 32-bit values for `uint_fast16_t`, but fails with GCC which uses 16-bit values.

**Comment by coderforlife** [comment]
This might be indicative of a different problem since I believe the max value for lims, last, and index is `1 << 15` (`0x8000`) which is less than 16-bits...

Since you have a specific example, can please send me the contents of `code_lengths` during the call to the function that doesn't work.

If this is supposed to fail (because it is purposely invalid input or something) then I may have to add some checks to make sure that we fail early instead of overflow.

**Comment by jibsen** [comment]
> If this is supposed to fail (because it is purposely invalid input or something) then I may have to add some checks to make sure that we fail early instead of overflow.

I am sorry, I should have noted that. The decompression test attempts to decompress random data to check that the decompression functions handle it without crashing.

**Comment by coderforlife** [comment]
Okay. I will think about a way to make this check as efficient as possible. Thanks for finding this

**Comment by coderforlife** [comment]
In MSVC, does it properly detect it during the following subsequent line?

    if (UNLIKELY(limit > sizeof(this->lens))) { return false; }

**Comment by jibsen** [comment]
Yes, it looks like it.

**Comment by coderforlife** [comment]
Thanks for identifying all the specifics of the problem. Should be all better now!

**Comment by jibsen** [comment]
Thanks, I am getting errors about a missing `Array.h` file with the current master, I assume you are in the middle of updating things. Could you give me a nodge when things are stable, and I will test it?

**Comment by coderforlife** [comment]
Can't believe I forgot to commit that new file! Done now. Thanks.

**Comment by jibsen** [comment]
The test is running fine locally now, thanks again for the fix.
