### ISSUE TITLE
Big endian unable to decompress data compressed on little-endian

### ISSUE THREAD

**Issue by nemequ** [coderforlife/ms-compress#32]
On BE (POWER8, to be precise), lznt1, xpress, and xpress-huffman are all unable to properly decompress data which was compressed on little-endian (x86_64).  All three codecs do work on BE so long as the data was also compressed on BE.

If you want, I can provide access to a VM for debugging and testing.

It's probably a bit overkill, but https://github.com/quixdb/squash/blob/master/plugins/crush/crush.c#L57 has some code for cross-platform endianness handling.

**Comment by coderforlife** [comment]
Can you send me a VM? I don't have access to any BE machines.

I do have code for handling different endians (see https://github.com/coderforlife/ms-compress/blob/master/include/mscomp/internal.h#L109), however I probably forget to use the macros (and just set/got the data directly) at one spot causing the problems.

**Comment by nemequ** [comment]
If you post your SSH public key I can create an account for you.

**Comment by coderforlife** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDPjhqM+fN5banenvcjzRuX7EivB3rGAh3ZoezmWRE9tlL3gmoTkC2Z7pe5/wr9Lbtjbj+78HRUWaXF+bg6D9X6eKu4x64XyWxYjkxKQhzl0h//RSqK/S3zNatnBs7cRW34ltDlS8/0EjQCR9XXPsprMeey/kA7ip3ZE6JXqrw7KQ==

**Comment by coderforlife** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDPjhqM+fN5banenvcjzRuX7EivB3rGAh3ZoezmWRE9tlL3gmoTkC2Z7pe5/wr9Lbtjbj+78HRUWaXF+bg6D9X6eKu4x64XyWxYjkxKQhzl0h//RSqK/S3zNatnBs7cRW34ltDlS8/0EjQCR9XXPsprMeey/kA7ip3ZE6JXqrw7KQ==

**Comment by nemequ** [comment]
coderforlife@140.211.168.20

**Comment by coderforlife** [comment]
Connected and built, but won't be able to work on this for a few days.

**Comment by coderforlife** [comment]
Looked into this briefly, and I compressed a sample 2.76KB text file and the compressed files were identical and both LE and BE machines were able to decompress LE and BE files so I have not be able to reproduce the problem yet. Can you please describe or send a sample file that compresses differently?

**Comment by nemequ** [comment]
Ah, it looks like it only happens with `-DMSCOMP_WITHOUT_UNALIGNED_ACCESS`.  Sorry, I should have tested that earlier, but I didn't think of it :/

https://github.com/quixdb/squash/tree/master/tests/data has sample data (lipsum.le.copy is the original data, lipsum.le.{lznt1,xpess,xpress-huffman} for data compressed on LE).

**Comment by nemequ** [comment]
BTW, modern GCC, clang, and msvc should all generate fast code for memcpy for unaligned access.  GCC < 6 had some issues on ARM, but they'

**Comment by coderforlife** [comment]
I believe it is fixed, at least with my minimal testing of each of the three algorithms now passes when compiled with `-DMSCOMP_WITHOUT_UNALIGNED_ACCESS`.

For the memcpy: I do use memcpy in lots of places, but for large LZ stretches it may be beneficial to use it, I am unsure though. It would just replace the loop at https://github.com/coderforlife/ms-compress/blob/e5d8cc5f4396be26c2c3ccc13fe59ce3a8885fea/include/mscomp/internal.h#L565 but wouldn't be a direct replacement.

**Comment by coderforlife** [comment]
One reason memcpy cannot be used is that in some implementations just map it to memmove which wouldn't work in several cases since frequently the ranges overlap and it behaves improperly for what I need.

**Comment by nemequ** [comment]
[Sorry, this ended up being a bit long…]

> I believe it is fixed, at least with my minimal testing of each of the three algorithms now passes when compiled with `-DMSCOMP_WITHOUT_UNALIGNED_ACCESS`.

Yep, works for me, too.  Thanks.

I'll probably shut down that VM soon, but if you ever want to test again just let me know.

> One reason memcpy cannot be used is that in some implementations just map it to memmove which wouldn't work in several cases since frequently the ranges overlap and it behaves improperly for what I need.

That doesn't quite make sense…  memcpy requires regions not overlap, memmove allows overlapping regions.  It should be safe to use memmove for an memcpy implementation, but not the other way around.  I guess what you meant is that memcpy wouldn't work because the ranges may overlap, period?

Anyways, I was really just referring to replacing unaligned fixed size loads with memcpy, not the entire loop.  Basically, instead of something like `(*((uint32_t*) foo))`, you can do `memcpy(bar, foo, sizeof(uint32_t))`. Yann Collet wrote [a good blog post about it](https://fastcompression.blogspot.fr/2015/08/accessing-unaligned-memory.html) a while back, and I recently posted [a quick story](http://encode.ru/threads/2221-LZFSE-New-Apple-Data-Compression?p=48866&viewfull=1#post48866) about why unaligned access can be dangerous.  Basically, with most compilers people use memcpy is just as fast as unaligned accesses, but safe.  icc and suncc generate sub-optimal assembly, but clang and msvc should be good.  gcc 6+ is good for all architectures, and older versions of gcc work well for x86/x86_64 but not ARM.

As for load + byte swap, GCC 5.3.1 (at least, I haven't tested anything older) and clang 3.8+ (but not 3.7) handle everything *very* well.  They recognize loading and shifting each byte as a byte swap operation (so if the data was BE, GCC will generate a bswap instruction).  That said, I'd still probably use `__builtin_bswap` just to be safe.  They also combine well with memcpy, so memcpy + shifting will generate movl + bswap on x86, and on POWER8 BE it actually generates a [lwbrx](https://www.ibm.com/support/knowledgecenter/ssw_aix_61/com.ibm.aix.aixassem/doc/alangref/idalangref_lwbrx_lbx_lwbri_instrs.htm).  So

```c
static uint32_t read32_swap_memcpy(const void* ptr) {
  uint32_t v;
  memcpy(&v, ptr, sizeof(uint32_t));
  v = __builtin_bswap32(v);
  return v;
}

static uint32_t read32_swap2_memcpy(const void* ptr) {
  uint32_t v;
  memcpy(&v, ptr, sizeof(uint32_t));
  v =
    (((uint8_t*)(&v))[0] << 24 |
    (((uint8_t*)(&v))[1] << 16) |
    (((uint8_t*)(&v))[2] << 8) |
    (((uint8_t*)(&v))[3] << 0));
  return v;
}

static uint32_t read32_swap_ub(const void* ptr) {
  uint32_t v = *((const uint32_t *) ptr);
  return __builtin_bswap32(v);
}
```

Will all generate the same thing: a single lwbrx instruction on POWER8 BE, or a movl on x86.  Putting it all together, I would probably do something like this:

```c
static inline uint32_t read32_le(const void* ptr) {
  uint32_t v;

  #if defined(MSCOMP_ALLOW_UNALIGNED)
    v = *((uint32_t*) ptr);
  #else
    memcpy(&v, ptr, sizeof(uint32_t));
  #endif

  #if defined(MSCOMP_BIG_ENDIAN)
    #if defined(__GNUC__) && ((__GNUC__ > 4) || (__GNUC__ == 4 && __GNUC_MINOR__ >= 4)) || (defined(__clang__) && defined(__has_builtin) && __has_builtin(__builtin_bswap32))
      v = __builtin_bswap32(v);
    #elif defined(_MSC_VER) && (_MSV_VER >= 1310)
      v = _byteswap_ulong(v);
    #else
      v =
        (((uint8_t*)(&v))[0] << 24 |
        (((uint8_t*)(&v))[1] << 16) |
        (((uint8_t*)(&v))[2] << 8) |
        (((uint8_t*)(&v))[3] << 0));
    #endif
  #elif defined(MSCOMP_PDP_ENDIAN)
    v =
      (((uint8_t*)(&v))[0] << 16 |
      (((uint8_t*)(&v))[1] << 24) |
      (((uint8_t*)(&v))[2] << 0) |
      (((uint8_t*)(&v))[3] << 8));
  #endif

  return v;
}
```

That should be as fast or slightly faster than what you have on the bswap side (it eliminates a bunch of loads on clang ≤ 3.7), and completely safe.  It may be slower for some compilers and architectures (GCC < 6 on ARM, icc, suncc, etc.), but if I were you I would be more concerned about safety; people could always define `MSCOMP_ALLOW_UNALIGNED` if they want to live dangerously, but IMHO it shouldn't be the default like it is now.

Replacing loops with memcpy or memmove is a more interesting question… while small, fixed-size memcpy calls are usually replaced by the compiler, if the size isn't known at compile libc's memcpy will be called.  libc's implementation may be *much* faster, especially if you aren't compiling with `-march=native` since it will likely [choose an implementation at runtime](https://sourceware.org/glibc/wiki/GNU_IFUNC) depending on whether the CPU supports SSE, AVX, NEON, etc.  OTOH, you take a hit for the function call, so the question is if a more optimized memcpy call can make up for the additional overhead.  I'm guessing the answer depends on the platform and the data.
