### ISSUE TITLE
Create Testing Code

### ISSUE THREAD

**Issue by coderforlife** [coderforlife/ms-compress#7]
Create cross-platform testing code to be able to test speed and accuracy.

**Comment by nemequ** [comment]
I'd be willing to port a couple of tests from Squash.  They're not much (especially when you don't include streaming, flushing, etc., but it should be a decent start.

I would also be willing to help set up [Travis](https://travis-ci.org/recent) if that would help.

**Comment by coderforlife** [comment]
I actually already have it, just not committed yet...

**Comment by coderforlife** [comment]
Testing code committed. Allows testing speed and accuracy of the provided algorithms and RTL algorithms (if on Windows).
