### ISSUE TITLE
mscomp-api-internal.h:40:17: fatal error: new.h: No such file or directory

### ISSUE THREAD

**Issue by nemequ** [coderforlife/ms-compress#8]
When compiling with g++ 4.9.2:

```
In file included from mscomp-api.h:52:0,
                 from lznt1.h:44,
                 from lznt1_compress.cpp:18:
mscomp-api-internal.h:40:17: fatal error: new.h: No such file or directory
 #include <new.h>
                 ^
compilation terminated.
```

`#include <new>` instead of `#include <new.h>` fixes it.

**Comment by nemequ** [comment]
But `<new>` requires C++, and that file gets included in the API which, AFAICT, is supposed to be C:

`lznt1.h` (and probably everything else, but that's what I'm doing first) includes `mscomp-api.h` which includes `mscomp-api-internal.h`.  I'm guessing `mscomp-api.h` including `mscomp-api-internal.h` is unintentional?

**Comment by nemequ** [comment]
After looking at the code a bit, `mscomp-api-internal.h` is only included when MSCOMP_API_EXPORT is defined.  I guess external consumers aren't supposed to define that, but without it there are lots of errors.  Some are pretty straightforward (like including `stddef.h` and `stdlib.h` for `size_t` and `malloc`), but other times code relies on macros and definitions from inside that file (like INLINE, FORCE_INLINE, UNLIKELY, etc.).

**Comment by coderforlife** [comment]
First, you are right, it should be `<new>` and not `<new.h>`. The latter being a Microsoft-specific header (apparently also available to MingW).

Next, to the more fundamental issue. I tried making the entire library C at one point but it was too much of a pain. So just the API is C while it does use C++ features internally.

So now that I wrote up the following paragraph, it seems all wrong and I will clean it up. Thanks for the input. Also, doesn't `<stdint.h>` end up (indirectly) defining `size_t`? If not, I do need to fix that.

The code is supposed to be compiled as a library (either static or dynamic) with MSCOMP_API_EXPORT. Then link to that library and include `mscomp.h` (or a compessor-specific one: `lznt1.h`, `xpress.h`, `xpress_huff.h`) and NOT define `MSCOMP_API_EXPORT`. You have to make sure that the `MSCOMP_WITH_`/`MSCOMP_WITHOUT_` are the same.

**Comment by nemequ** [comment]
> Also, doesn't <stdint.h> end up (indirectly) defining size_t? If not, I do need to fix that.

Nope.  Not here (Fedora 21, gcc 4.9, glibc 2.20), and I don't see anything in the C11 spec.

> I tried making the entire library C at one point but it was too much of a pain. So just the API is C while it does use C++ features internally.

That's fine.  It's the opposite of how I feel (C++ is too much of a pain), but as long as the API is accessible from C I don't have any objection.

Instead of having MSCOMP_API_EXPORT defined (or not) in the build system, why not just have internal files include `mscomp-api-internal.h`, which could then include `mscomp-api.h`.  Then external code would just include `mscomp-api.h`?  That would keep logic out of the build system so people can just pass the files to whatever compiler they want and have it just work…

I guess my problem (after the <new> thing is fixed) is that I'm trying to just compile everything (my code as well as ms-compress) at once instead of building a static library for ms-compress then linking to that.  That's just a much easier way for me to go right now because, well, cmake.  I guess in the future (when distros start packaging ms-compress) I might want the ability to use a shared library when available and fall back on an internal static library, at which point building a separate static library might make more sense, but right now it's just a PITA with no real upside.

**Comment by coderforlife** [comment]
Okay - will include stddef.h in public code.

Usually I enjoy using plain C as well, however a few things you made much easier with C++, like templates that I could then use the same set of functions but for different sized windows (which could be done in C using defines before including a header, but it was obnoxious).

You may notice (although lately I have been undoing this) I did write C-compliant code by even having the variable declarations all at the beginning of the code blocks (like old C).

I am in the process of separating internal from external and doing just what you say. And I did realize, when I was first replying, that your intention was to just bundle all the code, which is fine but it wasn't a scenario I had planned for. I am making it work for that.

**Comment by coderforlife** [comment]
Completed. Please see if it is more usable now.

**Comment by nemequ** [comment]
Yep, works well, thanks.
